[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = ["E", "W", "F", "B", "I"]
ignore = ["B905"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = ["src"]
