[tool.ruff]
src = ["src"]
line-length = 99
extend-exclude = [
  "src/chuliu_edmonds.py",
  "eval/conll18_ud_eval.py",
]

[tool.ruff.lint]
select = ["E", "W", "F", "B", "I"]
ignore = ["B905"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = ["src"]
